#ifndef _GMRVTKLIBS_HPP
#define _GMRVTKLIBS_HPP

//#define VTK_VER	510	//5.10
//#define VTK_VER	630	//6.3
//#define VTK_VER	700	//7.0
#define VTK_VER	711	//7.1.1

#if VTK_VER == 510
#pragma comment( lib, "vtksys.lib")
#pragma comment( lib, "vtkzlib.lib")
#pragma comment( lib, "vtkjpeg.lib")
#pragma comment( lib, "vtkpng.lib")
#pragma comment( lib, "vtktiff.lib")
#pragma comment( lib, "vtkexpat.lib")
#pragma comment( lib, "vtkfreetype.lib")
#pragma comment( lib, "vtklibxml2.lib")
#pragma comment( lib, "vtkDICOMParser.lib")
#pragma comment( lib, "vtkproj4.lib")
#pragma comment( lib, "vtkverdict.lib")
#pragma comment( lib, "vtkNetCDF.lib")
#pragma comment( lib, "vtkmetaio.lib")
#pragma comment( lib, "vtksqlite.lib")
#pragma comment( lib, "vtkexoIIc.lib")
#pragma comment( lib, "vtkalglib.lib")
#pragma comment( lib, "vtkftgl.lib")
#pragma comment( lib, "vtkCommon.lib")
#pragma comment( lib, "vtkFiltering.lib")
#pragma comment( lib, "vtkImaging.lib")
#pragma comment( lib, "vtkGraphics.lib")
#pragma comment( lib, "vtkGenericFiltering.lib")
#pragma comment( lib, "vtkIO.lib")
#pragma comment( lib, "vtkRendering.lib")
#pragma comment( lib, "vtkVolumeRendering.lib")
#pragma comment( lib, "vtkHybrid.lib")
#pragma comment( lib, "vtkWidgets.lib")
#pragma comment( lib, "vtkInfovis.lib")
#pragma comment( lib, "vtkGeovis.lib")
#pragma comment( lib, "vtkViews.lib")
#endif

#if VTK_VER == 630
//#pragma comment( lib, "vtksys-6.3.lib")
//#pragma comment( lib, "vtkzlib-6.3.lib")
//#pragma comment( lib, "vtkjpeg-6.3.lib")
//#pragma comment( lib, "vtkpng-6.3.lib")
//#pragma comment( lib, "vtktiff-6.3.lib")
//#pragma comment( lib, "vtkexpat-6.3.lib")
//#pragma comment( lib, "vtkfreetype-6.3.lib")
//#pragma comment( lib, "vtklibxml2-6.3.lib")
//#pragma comment( lib, "vtkDICOMParser-6.3.lib")
//#pragma comment( lib, "vtkproj4-6.3.lib")
//#pragma comment( lib, "vtkverdict-6.3.lib")
//#pragma comment( lib, "vtkNetCDF-6.3.lib")
//#pragma comment( lib, "vtkmetaio-6.3.lib")
//#pragma comment( lib, "vtksqlite-6.3.lib")
//#pragma comment( lib, "vtkexoIIc-6.3.lib")
//#pragma comment( lib, "vtkalglib-6.3.lib")
//#pragma comment( lib, "vtkftgl-6.3.lib")
//
////#pragma comment( lib, "vtkCommon-6.3.lib")
//#pragma comment( lib, "vtkCommonCore-6.3.lib")
//#pragma comment( lib, "vtkCommonDataModel-6.3.lib")
//#pragma comment( lib, "vtkCommonExecutionModel-6.3.lib")
//#pragma comment( lib, "vtkCommonTransforms-6.3.lib")
//#pragma comment( lib, "vtkCommonMisc-6.3.lib")
//#pragma comment( lib, "vtkCommonSystem-6.3.lib")
//#pragma comment( lib, "vtkCommonColor-6.3.lib")
//#pragma comment( lib, "vtkCommonMath-6.3.lib")
//#pragma comment( lib, "vtkCommonComputationalGeometry-6.3.lib")
//#pragma comment( lib, "vtkCommonTransforms-6.3.lib")
//
//#pragma comment( lib, "vtkChartsCore-6.3.lib")
//
//
////#pragma comment( lib, "vtkFiltering-6.3.lib")
//#pragma comment( lib, "vtkFiltersCore-6.3.lib")
//#pragma comment( lib, "vtkFiltersExtraction-6.3.lib")
//#pragma comment( lib, "vtkFiltersGeneral-6.3.lib")
//#pragma comment( lib, "vtkFiltersGeneric-6.3.lib")
//#pragma comment( lib, "vtkFiltersGeometry-6.3.lib")
//#pragma comment( lib, "vtkFiltersModeling-6.3.lib")
//#pragma comment( lib, "vtkFiltersParallel-6.3.lib")
//#pragma comment( lib, "vtkFiltersParallelImaging-6.3.lib")
//#pragma comment( lib, "vtkFiltersSources-6.3.lib")
//#pragma comment( lib, "vtkFiltersTexture-6.3.lib")
//#pragma comment( lib, "vtkFiltersFlowPaths-6.3.lib")
//#pragma comment( lib, "vtkFiltersImaging-6.3.lib")
//#pragma comment( lib, "vtkFiltersSelection-6.3.lib")
//
//
////#pragma comment( lib, "vtkImaging-6.3.lib")
//#pragma comment( lib, "vtkInfovisCore-6.3.lib")
//#pragma comment( lib, "vtkInteractionImage-6.3.lib")
//#pragma comment( lib, "vtkInteractionStyle-6.3.lib")
//#pragma comment( lib, "vtkInteractionStyle-6.3.lib")
//#pragma comment( lib, "vtkInteractionWidgets-6.3.lib")
//
////#pragma comment( lib, "vtkGraphics-6.3.lib")
//
////#pragma comment( lib, "vtkGenericFiltering-6.3.lib")
//
////#pragma comment( lib, "vtkIO-6.3.lib")
//#pragma comment( lib, "vtkIOCore-6.3.lib")
//#pragma comment( lib, "vtkIOMovie-6.3.lib")
//#pragma comment( lib, "vtkIOImage-6.3.lib")
//#pragma comment( lib, "vtkIOGeometry-6.3.lib")
//#pragma comment( lib, "vtkIOPLY-6.3.lib")
//#pragma comment( lib, "vtkIOExport-6.3.lib")
//#pragma comment( lib, "vtkIOImport-6.3.lib")
//
////#pragma comment( lib, "vtkRendering-6.3.lib")
//#pragma comment( lib, "vtkRenderingCore-6.3.lib")
//#pragma comment( lib, "vtkRenderingAnnotation-6.3.lib")
//#pragma comment( lib, "vtkRenderingFreeType-6.3.lib")
//#pragma comment( lib, "vtkRenderingContextOpenGL-6.3.lib")
//#pragma comment( lib, "vtkRenderingContext2D-6.3.lib")
//#pragma comment( lib, "vtkRenderingOpenGL-6.3.lib")
//#pragma comment( lib, "vtkRenderingImage-6.3.lib")
//
////#pragma comment( lib, "vtkVolumeRendering-6.3.lib")
//#pragma comment( lib, "vtkRenderingVolume-6.3.lib")
//#pragma comment( lib, "vtkRenderingVolumeOpenGL-6.3.lib")
//
////#pragma comment( lib, "vtkHybrid-6.3.lib")
//
////#pragma comment( lib, "vtkWidgets-6.3.lib")
////#pragma comment( lib, "vtkInteractionWidgets-6.3.lib")
//
////#pragma comment( lib, "vtkInfovis-6.3.lib")
//#pragma comment( lib, "vtkInfovisCore-6.3.lib")
//
////#pragma comment( lib, "vtkGeovis-6.3.lib")
//#pragma comment( lib, "vtkGeovisCore-6.3.lib")
//
////#pragma comment( lib, "vtkViews-6.3.lib")
//#pragma comment( lib, "vtkViewsCore-6.3.lib")
//
//
//#pragma comment( lib, "vtkDICOMParser-6.3.lib")
//
//#pragma comment( lib, "vtkImagingColor-6.3.lib")
//#pragma comment( lib, "vtkImagingCore-6.3.lib")
//#pragma comment( lib, "vtkImagingMath-6.3.lib")
//#pragma comment( lib, "vtkImagingSources-6.3.lib")
#pragma comment( lib, "vtkalglib-6.3.lib")
#pragma comment( lib, "vtkChartsCore-6.3.lib")
#pragma comment( lib, "vtkCommonColor-6.3.lib")
#pragma comment( lib, "vtkCommonComputationalGeometry-6.3.lib")
#pragma comment( lib, "vtkCommonCore-6.3.lib")
#pragma comment( lib, "vtkCommonDataModel-6.3.lib")
#pragma comment( lib, "vtkCommonExecutionModel-6.3.lib")
#pragma comment( lib, "vtkCommonMath-6.3.lib")
#pragma comment( lib, "vtkCommonMisc-6.3.lib")
#pragma comment( lib, "vtkCommonSystem-6.3.lib")
#pragma comment( lib, "vtkCommonTransforms-6.3.lib")
#pragma comment( lib, "vtkDICOMParser-6.3.lib")
#pragma comment( lib, "vtkDomainsChemistry-6.3.lib")
#pragma comment( lib, "vtkexoIIc-6.3.lib")
#pragma comment( lib, "vtkexpat-6.3.lib")
#pragma comment( lib, "vtkFiltersAMR-6.3.lib")
#pragma comment( lib, "vtkFiltersCore-6.3.lib")
#pragma comment( lib, "vtkFiltersExtraction-6.3.lib")
#pragma comment( lib, "vtkFiltersFlowPaths-6.3.lib")
#pragma comment( lib, "vtkFiltersGeneral-6.3.lib")
#pragma comment( lib, "vtkFiltersGeneric-6.3.lib")
#pragma comment( lib, "vtkFiltersGeometry-6.3.lib")
#pragma comment( lib, "vtkFiltersHybrid-6.3.lib")
#pragma comment( lib, "vtkFiltersHyperTree-6.3.lib")
#pragma comment( lib, "vtkFiltersImaging-6.3.lib")
#pragma comment( lib, "vtkFiltersModeling-6.3.lib")
#pragma comment( lib, "vtkFiltersParallel-6.3.lib")
#pragma comment( lib, "vtkFiltersParallelImaging-6.3.lib")
#pragma comment( lib, "vtkFiltersProgrammable-6.3.lib")
#pragma comment( lib, "vtkFiltersSelection-6.3.lib")
#pragma comment( lib, "vtkFiltersSMP-6.3.lib")
#pragma comment( lib, "vtkFiltersSources-6.3.lib")
#pragma comment( lib, "vtkFiltersStatistics-6.3.lib")
#pragma comment( lib, "vtkFiltersTexture-6.3.lib")
#pragma comment( lib, "vtkFiltersVerdict-6.3.lib")
#pragma comment( lib, "vtkfreetype-6.3.lib")
#pragma comment( lib, "vtkftgl-6.3.lib")
#pragma comment( lib, "vtkGeovisCore-6.3.lib")
#pragma comment( lib, "vtkgl2ps-6.3.lib")
#pragma comment( lib, "vtkhdf5-6.3.lib")
#pragma comment( lib, "vtkhdf5_hl-6.3.lib")
#pragma comment( lib, "vtkImagingColor-6.3.lib")
#pragma comment( lib, "vtkImagingCore-6.3.lib")
#pragma comment( lib, "vtkImagingFourier-6.3.lib")
#pragma comment( lib, "vtkImagingGeneral-6.3.lib")
#pragma comment( lib, "vtkImagingHybrid-6.3.lib")
#pragma comment( lib, "vtkImagingMath-6.3.lib")
#pragma comment( lib, "vtkImagingMorphological-6.3.lib")
#pragma comment( lib, "vtkImagingSources-6.3.lib")
#pragma comment( lib, "vtkImagingStatistics-6.3.lib")
#pragma comment( lib, "vtkImagingStencil-6.3.lib")
#pragma comment( lib, "vtkInfovisCore-6.3.lib")
#pragma comment( lib, "vtkInfovisLayout-6.3.lib")
#pragma comment( lib, "vtkInteractionImage-6.3.lib")
#pragma comment( lib, "vtkInteractionStyle-6.3.lib")
#pragma comment( lib, "vtkInteractionWidgets-6.3.lib")
#pragma comment( lib, "vtkIOAMR-6.3.lib")
#pragma comment( lib, "vtkIOCore-6.3.lib")
#pragma comment( lib, "vtkIOEnSight-6.3.lib")
#pragma comment( lib, "vtkIOExodus-6.3.lib")
#pragma comment( lib, "vtkIOExport-6.3.lib")
#pragma comment( lib, "vtkIOGeometry-6.3.lib")
#pragma comment( lib, "vtkIOImage-6.3.lib")
#pragma comment( lib, "vtkIOImport-6.3.lib")
#pragma comment( lib, "vtkIOInfovis-6.3.lib")
#pragma comment( lib, "vtkIOLegacy-6.3.lib")
#pragma comment( lib, "vtkIOLSDyna-6.3.lib")
#pragma comment( lib, "vtkIOMINC-6.3.lib")
#pragma comment( lib, "vtkIOMovie-6.3.lib")
#pragma comment( lib, "vtkIONetCDF-6.3.lib")
#pragma comment( lib, "vtkIOParallel-6.3.lib")
#pragma comment( lib, "vtkIOParallelXML-6.3.lib")
#pragma comment( lib, "vtkIOPLY-6.3.lib")
#pragma comment( lib, "vtkIOSQL-6.3.lib")
#pragma comment( lib, "vtkIOVideo-6.3.lib")
#pragma comment( lib, "vtkIOXML-6.3.lib")
#pragma comment( lib, "vtkIOXMLParser-6.3.lib")
#pragma comment( lib, "vtkjpeg-6.3.lib")
#pragma comment( lib, "vtkjsoncpp-6.3.lib")
#pragma comment( lib, "vtklibxml2-6.3.lib")
#pragma comment( lib, "vtkmetaio-6.3.lib")
#pragma comment( lib, "vtkNetCDF-6.3.lib")
#pragma comment( lib, "vtkNetCDF_cxx-6.3.lib")
#pragma comment( lib, "vtkoggtheora-6.3.lib")
#pragma comment( lib, "vtkParallelCore-6.3.lib")
#pragma comment( lib, "vtkpng-6.3.lib")
#pragma comment( lib, "vtkproj4-6.3.lib")
#pragma comment( lib, "vtkRenderingAnnotation-6.3.lib")
#pragma comment( lib, "vtkRenderingContext2D-6.3.lib")
#pragma comment( lib, "vtkRenderingContextOpenGL-6.3.lib")
#pragma comment( lib, "vtkRenderingCore-6.3.lib")
#pragma comment( lib, "vtkRenderingFreeType-6.3.lib")
#pragma comment( lib, "vtkRenderingGL2PS-6.3.lib")
#pragma comment( lib, "vtkRenderingImage-6.3.lib")
#pragma comment( lib, "vtkRenderingLabel-6.3.lib")
#pragma comment( lib, "vtkRenderingLIC-6.3.lib")
#pragma comment( lib, "vtkRenderingLOD-6.3.lib")
#pragma comment( lib, "vtkRenderingOpenGL-6.3.lib")
#pragma comment( lib, "vtkRenderingVolume-6.3.lib")
#pragma comment( lib, "vtkRenderingVolumeOpenGL-6.3.lib")
#pragma comment( lib, "vtksqlite-6.3.lib")
#pragma comment( lib, "vtksys-6.3.lib")
#pragma comment( lib, "vtktiff-6.3.lib")
#pragma comment( lib, "vtkverdict-6.3.lib")
#pragma comment( lib, "vtkViewsContext2D-6.3.lib")
#pragma comment( lib, "vtkViewsCore-6.3.lib")
#pragma comment( lib, "vtkViewsInfovis-6.3.lib")
#pragma comment( lib, "vtkzlib-6.3.lib")

#endif

#if VTK_VER == 700
#pragma comment( lib, "vtkalglib-7.0.lib")
#pragma comment( lib, "vtkChartsCore-7.0.lib")
#pragma comment( lib, "vtkCommonColor-7.0.lib")
#pragma comment( lib, "vtkCommonComputationalGeometry-7.0.lib")
#pragma comment( lib, "vtkCommonCore-7.0.lib")
#pragma comment( lib, "vtkCommonDataModel-7.0.lib")
#pragma comment( lib, "vtkCommonExecutionModel-7.0.lib")
#pragma comment( lib, "vtkCommonMath-7.0.lib")
#pragma comment( lib, "vtkCommonMisc-7.0.lib")
#pragma comment( lib, "vtkCommonSystem-7.0.lib")
#pragma comment( lib, "vtkCommonTransforms-7.0.lib")
#pragma comment( lib, "vtkDICOMParser-7.0.lib")
#pragma comment( lib, "vtkDomainsChemistry-7.0.lib")
#pragma comment( lib, "vtkDomainsChemistryOpenGL2-7.0.lib")
#pragma comment( lib, "vtkexoIIc-7.0.lib")
#pragma comment( lib, "vtkexpat-7.0.lib")
#pragma comment( lib, "vtkFiltersAMR-7.0.lib")
#pragma comment( lib, "vtkFiltersCore-7.0.lib")
#pragma comment( lib, "vtkFiltersExtraction-7.0.lib")
#pragma comment( lib, "vtkFiltersFlowPaths-7.0.lib")
#pragma comment( lib, "vtkFiltersGeneral-7.0.lib")
#pragma comment( lib, "vtkFiltersGeneric-7.0.lib")
#pragma comment( lib, "vtkFiltersGeometry-7.0.lib")
#pragma comment( lib, "vtkFiltersHybrid-7.0.lib")
#pragma comment( lib, "vtkFiltersHyperTree-7.0.lib")
#pragma comment( lib, "vtkFiltersImaging-7.0.lib")
#pragma comment( lib, "vtkFiltersModeling-7.0.lib")
#pragma comment( lib, "vtkFiltersParallel-7.0.lib")
#pragma comment( lib, "vtkFiltersParallelImaging-7.0.lib")
#pragma comment( lib, "vtkFiltersProgrammable-7.0.lib")
#pragma comment( lib, "vtkFiltersSelection-7.0.lib")
#pragma comment( lib, "vtkFiltersSMP-7.0.lib")
#pragma comment( lib, "vtkFiltersSources-7.0.lib")
#pragma comment( lib, "vtkFiltersStatistics-7.0.lib")
#pragma comment( lib, "vtkFiltersTexture-7.0.lib")
#pragma comment( lib, "vtkFiltersVerdict-7.0.lib")
#pragma comment( lib, "vtkfreetype-7.0.lib")
#pragma comment( lib, "vtkGeovisCore-7.0.lib")
#pragma comment( lib, "vtkglew-7.0.lib")
#pragma comment( lib, "vtkhdf5-7.0.lib")
#pragma comment( lib, "vtkhdf5_hl-7.0.lib")
#pragma comment( lib, "vtkImagingColor-7.0.lib")
#pragma comment( lib, "vtkImagingCore-7.0.lib")
#pragma comment( lib, "vtkImagingFourier-7.0.lib")
#pragma comment( lib, "vtkImagingGeneral-7.0.lib")
#pragma comment( lib, "vtkImagingHybrid-7.0.lib")
#pragma comment( lib, "vtkImagingMath-7.0.lib")
#pragma comment( lib, "vtkImagingMorphological-7.0.lib")
#pragma comment( lib, "vtkImagingSources-7.0.lib")
#pragma comment( lib, "vtkImagingStatistics-7.0.lib")
#pragma comment( lib, "vtkImagingStencil-7.0.lib")
#pragma comment( lib, "vtkInfovisCore-7.0.lib")
#pragma comment( lib, "vtkInfovisLayout-7.0.lib")
#pragma comment( lib, "vtkInteractionImage-7.0.lib")
#pragma comment( lib, "vtkInteractionStyle-7.0.lib")
#pragma comment( lib, "vtkInteractionWidgets-7.0.lib")
#pragma comment( lib, "vtkIOAMR-7.0.lib")
#pragma comment( lib, "vtkIOCore-7.0.lib")
#pragma comment( lib, "vtkIOEnSight-7.0.lib")
#pragma comment( lib, "vtkIOExodus-7.0.lib")
#pragma comment( lib, "vtkIOExport-7.0.lib")
#pragma comment( lib, "vtkIOGeometry-7.0.lib")
#pragma comment( lib, "vtkIOImage-7.0.lib")
#pragma comment( lib, "vtkIOImport-7.0.lib")
#pragma comment( lib, "vtkIOInfovis-7.0.lib")
#pragma comment( lib, "vtkIOLegacy-7.0.lib")
#pragma comment( lib, "vtkIOLSDyna-7.0.lib")
#pragma comment( lib, "vtkIOMINC-7.0.lib")
#pragma comment( lib, "vtkIOMovie-7.0.lib")
#pragma comment( lib, "vtkIONetCDF-7.0.lib")
#pragma comment( lib, "vtkIOParallel-7.0.lib")
#pragma comment( lib, "vtkIOParallelXML-7.0.lib")
#pragma comment( lib, "vtkIOPLY-7.0.lib")
#pragma comment( lib, "vtkIOSQL-7.0.lib")
#pragma comment( lib, "vtkIOVideo-7.0.lib")
#pragma comment( lib, "vtkIOXML-7.0.lib")
#pragma comment( lib, "vtkIOXMLParser-7.0.lib")
#pragma comment( lib, "vtkjpeg-7.0.lib")
#pragma comment( lib, "vtkjsoncpp-7.0.lib")
#pragma comment( lib, "vtklibxml2-7.0.lib")
#pragma comment( lib, "vtkmetaio-7.0.lib")
#pragma comment( lib, "vtkNetCDF-7.0.lib")
#pragma comment( lib, "vtkNetCDF_cxx-7.0.lib")
#pragma comment( lib, "vtkoggtheora-7.0.lib")
#pragma comment( lib, "vtkParallelCore-7.0.lib")
#pragma comment( lib, "vtkpng-7.0.lib")
#pragma comment( lib, "vtkproj4-7.0.lib")
#pragma comment( lib, "vtkRenderingAnnotation-7.0.lib")
#pragma comment( lib, "vtkRenderingContext2D-7.0.lib")
#pragma comment( lib, "vtkRenderingContextOpenGL2-7.0.lib")
#pragma comment( lib, "vtkRenderingCore-7.0.lib")
#pragma comment( lib, "vtkRenderingFreeType-7.0.lib")
#pragma comment( lib, "vtkRenderingImage-7.0.lib")
#pragma comment( lib, "vtkRenderingLabel-7.0.lib")
#pragma comment( lib, "vtkRenderingLOD-7.0.lib")
#pragma comment( lib, "vtkRenderingOpenGL2-7.0.lib")
#pragma comment( lib, "vtkRenderingVolume-7.0.lib")
#pragma comment( lib, "vtkRenderingVolumeOpenGL2-7.0.lib")
#pragma comment( lib, "vtksqlite-7.0.lib")
#pragma comment( lib, "vtksys-7.0.lib")
#pragma comment( lib, "vtktiff-7.0.lib")
#pragma comment( lib, "vtkverdict-7.0.lib")
#pragma comment( lib, "vtkViewsContext2D-7.0.lib")
#pragma comment( lib, "vtkViewsCore-7.0.lib")
#pragma comment( lib, "vtkViewsInfovis-7.0.lib")
#pragma comment( lib, "vtkzlib-7.0.lib")
#endif

#if VTK_VER == 711
#pragma comment( lib, "vtkalglib-7.1.lib")
#pragma comment( lib, "vtkChartsCore-7.1.lib")
#pragma comment( lib, "vtkCommonColor-7.1.lib")
#pragma comment( lib, "vtkCommonComputationalGeometry-7.1.lib")
#pragma comment( lib, "vtkCommonCore-7.1.lib")
#pragma comment( lib, "vtkCommonDataModel-7.1.lib")
#pragma comment( lib, "vtkCommonExecutionModel-7.1.lib")
#pragma comment( lib, "vtkCommonMath-7.1.lib")
#pragma comment( lib, "vtkCommonMisc-7.1.lib")
#pragma comment( lib, "vtkCommonSystem-7.1.lib")
#pragma comment( lib, "vtkCommonTransforms-7.1.lib")
#pragma comment( lib, "vtkDICOMParser-7.1.lib")
#pragma comment( lib, "vtkDomainsChemistry-7.1.lib")
#pragma comment( lib, "vtkDomainsChemistryOpenGL2-7.1.lib")
#pragma comment( lib, "vtkexoIIc-7.1.lib")
#pragma comment( lib, "vtkexpat-7.1.lib")
#pragma comment( lib, "vtkFiltersAMR-7.1.lib")
#pragma comment( lib, "vtkFiltersCore-7.1.lib")
#pragma comment( lib, "vtkFiltersExtraction-7.1.lib")
#pragma comment( lib, "vtkFiltersFlowPaths-7.1.lib")
#pragma comment( lib, "vtkFiltersGeneral-7.1.lib")
#pragma comment( lib, "vtkFiltersGeneric-7.1.lib")
#pragma comment( lib, "vtkFiltersGeometry-7.1.lib")
#pragma comment( lib, "vtkFiltersHybrid-7.1.lib")
#pragma comment( lib, "vtkFiltersHyperTree-7.1.lib")
#pragma comment( lib, "vtkFiltersImaging-7.1.lib")
#pragma comment( lib, "vtkFiltersModeling-7.1.lib")
#pragma comment( lib, "vtkFiltersParallel-7.1.lib")
#pragma comment( lib, "vtkFiltersParallelImaging-7.1.lib")
#pragma comment( lib, "vtkFiltersProgrammable-7.1.lib")
#pragma comment( lib, "vtkFiltersSelection-7.1.lib")
#pragma comment( lib, "vtkFiltersSMP-7.1.lib")
#pragma comment( lib, "vtkFiltersSources-7.1.lib")
#pragma comment( lib, "vtkFiltersStatistics-7.1.lib")
#pragma comment( lib, "vtkFiltersTexture-7.1.lib")
#pragma comment( lib, "vtkFiltersVerdict-7.1.lib")
#pragma comment( lib, "vtkfreetype-7.1.lib")
#pragma comment( lib, "vtkGeovisCore-7.1.lib")
#pragma comment( lib, "vtkglew-7.1.lib")
#pragma comment( lib, "vtkhdf5-7.1.lib")
#pragma comment( lib, "vtkhdf5_hl-7.1.lib")
#pragma comment( lib, "vtkImagingColor-7.1.lib")
#pragma comment( lib, "vtkImagingCore-7.1.lib")
#pragma comment( lib, "vtkImagingFourier-7.1.lib")
#pragma comment( lib, "vtkImagingGeneral-7.1.lib")
#pragma comment( lib, "vtkImagingHybrid-7.1.lib")
#pragma comment( lib, "vtkImagingMath-7.1.lib")
#pragma comment( lib, "vtkImagingMorphological-7.1.lib")
#pragma comment( lib, "vtkImagingSources-7.1.lib")
#pragma comment( lib, "vtkImagingStatistics-7.1.lib")
#pragma comment( lib, "vtkImagingStencil-7.1.lib")
#pragma comment( lib, "vtkInfovisCore-7.1.lib")
#pragma comment( lib, "vtkInfovisLayout-7.1.lib")
#pragma comment( lib, "vtkInteractionImage-7.1.lib")
#pragma comment( lib, "vtkInteractionStyle-7.1.lib")
#pragma comment( lib, "vtkInteractionWidgets-7.1.lib")
#pragma comment( lib, "vtkIOAMR-7.1.lib")
#pragma comment( lib, "vtkIOCore-7.1.lib")
#pragma comment( lib, "vtkIOEnSight-7.1.lib")
#pragma comment( lib, "vtkIOExodus-7.1.lib")
#pragma comment( lib, "vtkIOExport-7.1.lib")
#pragma comment( lib, "vtkIOGeometry-7.1.lib")
#pragma comment( lib, "vtkIOImage-7.1.lib")
#pragma comment( lib, "vtkIOImport-7.1.lib")
#pragma comment( lib, "vtkIOInfovis-7.1.lib")
#pragma comment( lib, "vtkIOLegacy-7.1.lib")
#pragma comment( lib, "vtkIOLSDyna-7.1.lib")
#pragma comment( lib, "vtkIOMINC-7.1.lib")
#pragma comment( lib, "vtkIOMovie-7.1.lib")
#pragma comment( lib, "vtkIONetCDF-7.1.lib")
#pragma comment( lib, "vtkIOParallel-7.1.lib")
#pragma comment( lib, "vtkIOParallelXML-7.1.lib")
#pragma comment( lib, "vtkIOPLY-7.1.lib")
#pragma comment( lib, "vtkIOSQL-7.1.lib")
#pragma comment( lib, "vtkIOVideo-7.1.lib")
#pragma comment( lib, "vtkIOXML-7.1.lib")
#pragma comment( lib, "vtkIOXMLParser-7.1.lib")
#pragma comment( lib, "vtkjpeg-7.1.lib")
#pragma comment( lib, "vtkjsoncpp-7.1.lib")
#pragma comment( lib, "vtklibxml2-7.1.lib")
#pragma comment( lib, "vtkmetaio-7.1.lib")
#pragma comment( lib, "vtkNetCDF-7.1.lib")
#pragma comment( lib, "vtkNetCDF_cxx-7.1.lib")
#pragma comment( lib, "vtkoggtheora-7.1.lib")
#pragma comment( lib, "vtkParallelCore-7.1.lib")
#pragma comment( lib, "vtkpng-7.1.lib")
#pragma comment( lib, "vtkproj4-7.1.lib")
#pragma comment( lib, "vtkRenderingAnnotation-7.1.lib")
#pragma comment( lib, "vtkRenderingContext2D-7.1.lib")
#pragma comment( lib, "vtkRenderingContextOpenGL2-7.1.lib")
#pragma comment( lib, "vtkRenderingCore-7.1.lib")
#pragma comment( lib, "vtkRenderingFreeType-7.1.lib")
#pragma comment( lib, "vtkRenderingImage-7.1.lib")
#pragma comment( lib, "vtkRenderingLabel-7.1.lib")
#pragma comment( lib, "vtkRenderingLOD-7.1.lib")
#pragma comment( lib, "vtkRenderingOpenGL2-7.1.lib")
#pragma comment( lib, "vtkRenderingVolume-7.1.lib")
#pragma comment( lib, "vtkRenderingVolumeOpenGL2-7.1.lib")
#pragma comment( lib, "vtksqlite-7.1.lib")
#pragma comment( lib, "vtksys-7.1.lib")
#pragma comment( lib, "vtktiff-7.1.lib")
#pragma comment( lib, "vtkverdict-7.1.lib")
#pragma comment( lib, "vtkViewsContext2D-7.1.lib")
#pragma comment( lib, "vtkViewsCore-7.1.lib")
#pragma comment( lib, "vtkViewsInfovis-7.1.lib")
#pragma comment( lib, "vtkzlib-7.1.lib")
#endif

#ifndef NO_LINK_LIBS
#ifdef _WIN64
#ifdef _DEBUG
#pragma comment( lib, "../../vtkFreeWrapper/util/lib/Debug/64bit/vtkWrapperLib.lib" )
#else
#pragma comment( lib, "../../vtkFreeWrapper/util/lib/Release/64bit/vtkWrapperLib.lib" )
#endif
#else
#ifdef _DEBUG
#pragma comment( lib, "../../vtkFreeWrapper/util/lib/Debug/32bit/vtkWrapperLib.lib" )
#else
#pragma comment( lib, "../../vtkFreeWrapper/util/lib/Release/32bit/vtkWrapperLib.lib" )
#endif
#endif
#endif

#ifdef WIN32
#pragma comment( lib, "opengl32.lib" )
#pragma comment( lib, "vfw32.lib")
#endif

#endif
